#使用朱大仙儿 build的带有curl的apline
FROM alpine
LABEL maintainer="rubinus.chu@mail.com"

#接受参数,把源代码git commitid放到镜像内
ARG BUILD
LABEL VERSION=$BUILD

#支持的架构变量，不用传值，docker自动获取

#设置工作目录
WORKDIR /opt/origin/

#添加可执行文件
COPY build/origin-linux-arm64 /opt/origin/
COPY entrypoint.sh /opt/origin/

#添加配置及html等
COPY configs /opt/origin/configs
COPY web /opt/origin/web

RUN ["chmod", "+x", "origin-linux-arm64"]
RUN ["chmod", "+x", "entrypoint.sh"]

#设置Web端口，一般不用更改
EXPOSE 80

#设置GRPC端口，一般不用更改
EXPOSE 50051

ENTRYPOINT ["/opt/origin/origin-linux-arm64","--env=container"]
