// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld.proto

package pb_helloworld

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  uint32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Requests             []*HelloRequest_Request `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetAge() uint32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *HelloRequest) GetRequests() []*HelloRequest_Request {
	if m != nil {
		return m.Requests
	}
	return nil
}

type HelloRequest_Request struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Ins                  []string `protobuf:"bytes,3,rep,name=ins,proto3" json:"ins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest_Request) Reset()         { *m = HelloRequest_Request{} }
func (m *HelloRequest_Request) String() string { return proto.CompactTextString(m) }
func (*HelloRequest_Request) ProtoMessage()    {}
func (*HelloRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{0, 0}
}

func (m *HelloRequest_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest_Request.Unmarshal(m, b)
}
func (m *HelloRequest_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest_Request.Marshal(b, m, deterministic)
}
func (m *HelloRequest_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest_Request.Merge(m, src)
}
func (m *HelloRequest_Request) XXX_Size() int {
	return xxx_messageInfo_HelloRequest_Request.Size(m)
}
func (m *HelloRequest_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest_Request.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest_Request proto.InternalMessageInfo

func (m *HelloRequest_Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HelloRequest_Request) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HelloRequest_Request) GetIns() []string {
	if m != nil {
		return m.Ins
	}
	return nil
}

type Info struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Money                float64  `protobuf:"fixed64,2,opt,name=money,proto3" json:"money,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{1}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Info) GetMoney() float64 {
	if m != nil {
		return m.Money
	}
	return 0
}

type HelloResponse struct {
	Message              string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Infos                []*Info          `protobuf:"bytes,2,rep,name=Infos,proto3" json:"Infos,omitempty"`
	Ans                  []string         `protobuf:"bytes,3,rep,name=ans,proto3" json:"ans,omitempty"`
	Projects             map[string]int32 `protobuf:"bytes,4,rep,name=projects,proto3" json:"projects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	MyMap                map[string]*Info `protobuf:"bytes,5,rep,name=myMap,proto3" json:"myMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{2}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloResponse) GetInfos() []*Info {
	if m != nil {
		return m.Infos
	}
	return nil
}

func (m *HelloResponse) GetAns() []string {
	if m != nil {
		return m.Ans
	}
	return nil
}

func (m *HelloResponse) GetProjects() map[string]int32 {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *HelloResponse) GetMyMap() map[string]*Info {
	if m != nil {
		return m.MyMap
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pb.helloworld.HelloRequest")
	proto.RegisterType((*HelloRequest_Request)(nil), "pb.helloworld.HelloRequest.Request")
	proto.RegisterType((*Info)(nil), "pb.helloworld.Info")
	proto.RegisterType((*HelloResponse)(nil), "pb.helloworld.HelloResponse")
	proto.RegisterMapType((map[string]*Info)(nil), "pb.helloworld.HelloResponse.MyMapEntry")
	proto.RegisterMapType((map[string]int32)(nil), "pb.helloworld.HelloResponse.ProjectsEntry")
}

func init() { proto.RegisterFile("helloworld/helloworld.proto", fileDescriptor_73149fedf49f4319) }

var fileDescriptor_73149fedf49f4319 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xbe, 0xd3, 0x34, 0xde, 0xf6, 0x5c, 0x03, 0xd7, 0xd1, 0x45, 0xc8, 0x95, 0xb1, 0x44, 0xc4,
	0x5e, 0x17, 0x29, 0xd4, 0x8d, 0x28, 0x22, 0x54, 0xfc, 0x5b, 0x14, 0x64, 0xba, 0x10, 0xc4, 0x4d,
	0x5a, 0xc7, 0x1a, 0x9b, 0x64, 0x62, 0x26, 0xad, 0xe4, 0x05, 0x7c, 0x16, 0x9f, 0xc1, 0x27, 0xe8,
	0xd2, 0x27, 0x90, 0x26, 0x4b, 0x57, 0x2e, 0x5d, 0xca, 0xcc, 0x24, 0x4d, 0x2b, 0xb5, 0xab, 0x9c,
	0xbf, 0xef, 0xfb, 0xce, 0xf9, 0xc8, 0xc0, 0xc5, 0x47, 0x16, 0x86, 0xfc, 0x0b, 0x4f, 0xc3, 0xf7,
	0x83, 0x26, 0xf4, 0x92, 0x94, 0x67, 0x1c, 0x5b, 0xc9, 0xd4, 0x6b, 0x8a, 0x0e, 0xcc, 0xf9, 0x9c,
	0xeb, 0x96, 0xfb, 0x1d, 0xc1, 0xd5, 0x97, 0xb2, 0x45, 0xd9, 0xe7, 0x25, 0x13, 0x19, 0xc6, 0xd0,
	0x8e, 0xfd, 0x88, 0xd9, 0xa8, 0x87, 0xfa, 0x5d, 0xaa, 0x62, 0x7c, 0x0e, 0x86, 0x3f, 0x67, 0x76,
	0xab, 0x87, 0xfa, 0x16, 0x95, 0x21, 0x7e, 0x02, 0x9d, 0x54, 0x03, 0x84, 0x6d, 0xf4, 0x8c, 0xfe,
	0xd9, 0xf0, 0xb6, 0xb7, 0x27, 0xe2, 0xed, 0x92, 0x7a, 0xd5, 0x97, 0x6e, 0x41, 0xce, 0x53, 0x38,
	0xad, 0x15, 0xcf, 0xc1, 0x58, 0xa6, 0x61, 0x25, 0x28, 0x43, 0x7c, 0x03, 0xcc, 0x2c, 0xc8, 0x42,
	0xad, 0xd8, 0xa5, 0x3a, 0x91, 0x73, 0x41, 0xac, 0xe5, 0xba, 0x54, 0x86, 0xee, 0x10, 0xda, 0xaf,
	0xe2, 0x0f, 0x5c, 0xce, 0xb3, 0xc8, 0x0f, 0x6a, 0x0e, 0x9d, 0xc8, 0x6a, 0xc4, 0x63, 0x96, 0x2b,
	0x16, 0x44, 0x75, 0xe2, 0x7e, 0x35, 0xc0, 0xaa, 0x76, 0x13, 0x09, 0x8f, 0x05, 0xc3, 0x77, 0xe0,
	0x34, 0x62, 0x42, 0xc8, 0x0b, 0x15, 0x7e, 0x74, 0xf6, 0xeb, 0xe7, 0xad, 0xba, 0x44, 0xeb, 0x00,
	0x5f, 0x82, 0x29, 0xc5, 0x84, 0xdd, 0x52, 0xf7, 0x5e, 0xff, 0xe7, 0x5e, 0xd9, 0xa3, 0x7a, 0x42,
	0xf9, 0xd5, 0x6c, 0xea, 0xc7, 0x02, 0x3f, 0x87, 0x4e, 0x92, 0xf2, 0x4f, 0x6c, 0x96, 0x09, 0xbb,
	0xad, 0xf0, 0xf7, 0x0e, 0xfb, 0xa5, 0x77, 0xf2, 0x5e, 0x57, 0xc3, 0xcf, 0xe2, 0x2c, 0xcd, 0xe9,
	0x16, 0x8b, 0x1f, 0x83, 0x19, 0xe5, 0x63, 0x3f, 0xb1, 0x4d, 0x45, 0x72, 0xf7, 0x28, 0xc9, 0x58,
	0x4e, 0x6a, 0x06, 0x8d, 0x72, 0x1e, 0x81, 0xb5, 0xc7, 0x2c, 0x37, 0x5d, 0xb0, 0xbc, 0xf6, 0x7e,
	0xc1, 0x72, 0xe9, 0xda, 0xca, 0x0f, 0x97, 0xda, 0x7b, 0x93, 0xea, 0xe4, 0x61, 0xeb, 0x01, 0x72,
	0xc6, 0x00, 0x0d, 0xe3, 0x01, 0xe4, 0xe5, 0x2e, 0xf2, 0x7f, 0x06, 0x6d, 0xe9, 0x86, 0xef, 0xe0,
	0x9a, 0x5a, 0xf7, 0x8d, 0xec, 0x4e, 0x58, 0xba, 0x0a, 0x66, 0x0c, 0xbf, 0x80, 0xce, 0xc4, 0xcf,
	0x55, 0x1d, 0x5f, 0x1c, 0xf9, 0xa3, 0x9c, 0x9b, 0xc7, 0x2e, 0x77, 0x4f, 0x46, 0x83, 0x75, 0x41,
	0x4e, 0x36, 0x05, 0x41, 0xbf, 0x0b, 0x82, 0xfe, 0x14, 0x04, 0x7d, 0x2b, 0x09, 0x5a, 0x97, 0x04,
	0xfd, 0x28, 0x09, 0xda, 0x94, 0x04, 0xbd, 0xdd, 0x7f, 0x14, 0xd3, 0x2b, 0xea, 0x3d, 0xdc, 0xff,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x57, 0x85, 0xa4, 0x98, 0x49, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloWorldServiceClient is the client API for HelloWorldService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloWorldServiceClient interface {
	//HelloRequest 改名为你的 XXXXXRequest
	//HelloResponse 改名为你的 XXXXXResponse
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloWorldServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloWorldServiceClient(cc *grpc.ClientConn) HelloWorldServiceClient {
	return &helloWorldServiceClient{cc}
}

func (c *helloWorldServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/pb.helloworld.HelloWorldService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWorldServiceServer is the server API for HelloWorldService service.
type HelloWorldServiceServer interface {
	//HelloRequest 改名为你的 XXXXXRequest
	//HelloResponse 改名为你的 XXXXXResponse
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterHelloWorldServiceServer(s *grpc.Server, srv HelloWorldServiceServer) {
	s.RegisterService(&_HelloWorldService_serviceDesc, srv)
}

func _HelloWorldService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWorldServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.helloworld.HelloWorldService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWorldServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloWorldService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.helloworld.HelloWorldService",
	HandlerType: (*HelloWorldServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloWorldService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
