// Code generated by MockGen. DO NOT EDIT.
// Source: weather.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ioparams "github.com/gitcpu-io/origin/models/ioparams"
	weather "github.com/gitcpu-io/origin/models/weather"
	gomock "github.com/golang/mock/gomock"
)

// MockWeatherer is a mock of Weatherer interface.
type MockWeatherer struct {
	ctrl     *gomock.Controller
	recorder *MockWeathererMockRecorder
}

// MockWeathererMockRecorder is the mock recorder for MockWeatherer.
type MockWeathererMockRecorder struct {
	mock *MockWeatherer
}

// NewMockWeatherer creates a new mock instance.
func NewMockWeatherer(ctrl *gomock.Controller) *MockWeatherer {
	mock := &MockWeatherer{ctrl: ctrl}
	mock.recorder = &MockWeathererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherer) EXPECT() *MockWeathererMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockWeatherer) Insert(ctx context.Context, req *ioparams.WeatherRequest) (*weather.Weather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, req)
	ret0, _ := ret[0].(*weather.Weather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockWeathererMockRecorder) Insert(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockWeatherer)(nil).Insert), ctx, req)
}

// List mocks base method.
func (m *MockWeatherer) List(ctx context.Context, city string) ([]*weather.Weather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, city)
	ret0, _ := ret[0].([]*weather.Weather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWeathererMockRecorder) List(ctx, city interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWeatherer)(nil).List), ctx, city)
}
